name: Update Weather Forecast HTML

on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes all day long
  workflow_dispatch:

jobs:
  update-weather-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather script
        run: |
          python get_weather.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add weather_forecast.html
          git commit -m "Update Weather Forecast HTML"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
